# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_categories', models.CharField(choices=[('Alcohol', 'Alcohol'), ('American', 'American'), ('Asian', 'Asian'), ('BBQ', 'BBQ'), ('Bakery', 'Bakery'), ('Chicken', 'Chicken'), ('Chinese', 'Chinese'), ('CoffeeTea', 'Coffee and Tea'), ('Dessert', 'Dessert'), ('Eclectic', 'Eclectic'), ('GlutenFree', 'Gluten-Free'), ('Grill', 'Grill'), ('Halal', 'Halal'), ('Hamburgers', 'Hamburgers'), ('Healthy', 'Healthy'), ('HotDogs', 'Hot Dogs'), ('IcCream', 'Ice Cream'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('LatinAmerican', 'Latin American'), ('LunchSpecials', 'Lunch Specials'), ('Mediterranean', 'Mediterranean'), ('Mexican', 'Mexican'), ('MiddlEastern', 'Middle Eastern'), ('NeAmerican', 'New American'), ('Noodles', 'Noodles'), ('Pakistani', 'Pakistani'), ('Pasta', 'Pasta'), ('Pizza', 'Pizza'), ('PubFood', 'Pub Food'), ('Ribs', 'Ribs'), ('Salads', 'Salads'), ('Sandwiches', 'Sandwiches'), ('Seafood', 'Seafood'), ('SmoothiesJuices', 'Smoothies and Juices'), ('Soup', 'Soup'), ('Southern', 'Southern'), ('Spanish', 'Spanish'), ('Steak', 'Steak'), ('Subs', 'Subs'), ('Sushi', 'Sushi'), ('Szechwan', 'Szechwan'), ('Tapas', 'Tapas'), ('Thai', 'Thai'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Vietnamese', 'Vietnamese'), ('Wings', 'Wings'), ('Wraps', 'Wraps')], max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Grubber'),
        ),
        migrations.AlterField(
            model_name='restaurantaddress',
            name='address_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(to='restaurants.RestaurantCategory'),
        ),
    ]
