# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20171218_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.DeleteModel(
            name='RestaurantCategory',
        ),
    ]
