# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20171218_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
