# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_delete_addressmanager'),
        ('restaurants', '0005_auto_20171218_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Grubber')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('address_label', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_addresses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='restaurants.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_categories', models.CharField(choices=[('Alcohol', 'Alcohol'), ('American', 'American'), ('Asian', 'Asian'), ('BBQ', 'BBQ'), ('Bakery', 'Bakery'), ('Chicken', 'Chicken'), ('Chinese', 'Chinese'), ('CoffeeTea', 'Coffee and Tea'), ('Dessert', 'Dessert'), ('Eclectic', 'Eclectic'), ('GlutenFree', 'Gluten-Free'), ('Grill', 'Grill'), ('Halal', 'Halal'), ('Hamburgers', 'Hamburgers'), ('Healthy', 'Healthy'), ('HotDogs', 'Hot Dogs'), ('IcCream', 'Ice Cream'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('LatinAmerican', 'Latin American'), ('LunchSpecials', 'Lunch Specials'), ('Mediterranean', 'Mediterranean'), ('Mexican', 'Mexican'), ('MiddlEastern', 'Middle Eastern'), ('NeAmerican', 'New American'), ('Noodles', 'Noodles'), ('Pakistani', 'Pakistani'), ('Pasta', 'Pasta'), ('Pizza', 'Pizza'), ('PubFood', 'Pub Food'), ('Ribs', 'Ribs'), ('Salads', 'Salads'), ('Sandwiches', 'Sandwiches'), ('Seafood', 'Seafood'), ('SmoothiesJuices', 'Smoothies and Juices'), ('Soup', 'Soup'), ('Southern', 'Southern'), ('Spanish', 'Spanish'), ('Steak', 'Steak'), ('Subs', 'Subs'), ('Sushi', 'Sushi'), ('Szechwan', 'Szechwan'), ('Tapas', 'Tapas'), ('Thai', 'Thai'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Vietnamese', 'Vietnamese'), ('Wings', 'Wings'), ('Wraps', 'Wraps')], max_length=100, null=True)),
            ],
        ),
    ]
