# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_menu_restaurant_restaurantaddress_restaurantcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(to='restaurants.RestaurantCategory'),
        ),
    ]
