# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='restaurantaddress',
            name='rest_addresses',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RestaurantAddress',
        ),
    ]
