# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20171219_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcategory',
            name='restaurant_categories',
            field=models.CharField(choices=[('Sushi', 'Sushi'), ('BBQ', 'BBQ'), ('Asian', 'Asian'), ('Chicken', 'Chicken'), ('Mediterranean', 'Mediterranean'), ('PubFood', 'Pub Food'), ('Vietnamese', 'Vietnamese'), ('Spanish', 'Spanish'), ('Sandwiches', 'Sandwiches'), ('HotDogs', 'Hot Dogs'), ('Pasta', 'Pasta'), ('SmoothiesJuices', 'Smoothies and Juices'), ('Soup', 'Soup'), ('Vegetarian', 'Vegetarian'), ('Steak', 'Steak'), ('Indian', 'Indian'), ('Alcohol', 'Alcohol'), ('CoffeeTea', 'Coffee and Tea'), ('Salads', 'Salads'), ('Seafood', 'Seafood'), ('Halal', 'Halal'), ('Szechwan', 'Szechwan'), ('Hamburgers', 'Hamburgers'), ('Wings', 'Wings'), ('Japanese', 'Japanese'), ('Grill', 'Grill'), ('Southern', 'Southern'), ('Vegan', 'Vegan'), ('Chinese', 'Chinese'), ('LunchSpecials', 'Lunch Specials'), ('GlutenFree', 'Gluten-Free'), ('Wraps', 'Wraps'), ('IcCream', 'Ice Cream'), ('Eclectic', 'Eclectic'), ('MiddlEastern', 'Middle Eastern'), ('Noodles', 'Noodles'), ('Thai', 'Thai'), ('Tapas', 'Tapas'), ('NeAmerican', 'New American'), ('Pakistani', 'Pakistani'), ('Ribs', 'Ribs'), ('Mexican', 'Mexican'), ('LatinAmerican', 'Latin American'), ('Dessert', 'Dessert'), ('Pizza', 'Pizza'), ('Healthy', 'Healthy'), ('Bakery', 'Bakery'), ('American', 'American'), ('Italian', 'Italian'), ('Subs', 'Subs')], max_length=100),
        ),
    ]
