# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_auto_20171221_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos/'),
        ),
    ]
