# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_restaurant_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
