# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171218_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='UserAddress',
        ),
        migrations.AddField(
            model_name='grubber',
            name='is_rest_owner',
            field=models.BooleanField(default=False),
        ),
    ]
