# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171218_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressManager',
        ),
    ]
