# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menu_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_type',
            new_name='menu_name',
        ),
    ]
